id: A964EF41F
title: 'The Drum of Deathlessness: A Prayer for the Long Life of Minling Chung Rinpoche'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:47:35.610125
  last_modified_at: 2022-03-01 00:47:35.610130
