id: A964EF41F
title: A Plaintive Prayer to Guru Rinpoche
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:47:35.607702
  last_modified_at: 2022-03-01 00:47:35.607708
